import type { SeedExam, SeedQuestion } from "./types";

const beginnerQuestions: SeedQuestion[] = [
  { type: "MULTIPLE_CHOICE", topic: "Variables", difficulty: "EASY",
    prompt: "Which symbol assigns a value to a variable in Python?",
    options: ["==", "=>", "=", ":="], answer: "=",
    explanation: "`=` assigns; `==` compares." },
  { type: "TRUE_FALSE", topic: "Variables", difficulty: "EASY",
    prompt: "Variable names in Python are case-sensitive.",
    answer: "true", explanation: "`age` and `Age` are different variables." },
  { type: "MULTIPLE_CHOICE", topic: "Data Types", difficulty: "EASY",
    prompt: "What type is the value True?",
    options: ["int", "str", "bool", "float"], answer: "bool",
    explanation: "True/False are boolean (`bool`) values." },
  { type: "FILL_BLANK", topic: "Data Types", difficulty: "EASY",
    prompt: "Convert text to integer: n = ____(\"7\")", answer: "int",
    explanation: "`int(\"7\")` returns the integer 7." },
  { type: "CODE_OUTPUT", topic: "Data Types", difficulty: "MEDIUM",
    prompt: "What is printed?", code: "print(type(3.0).__name__)",
    answer: "float", explanation: "3.0 has a decimal point, so it's a float." },
  { type: "CODE_OUTPUT", topic: "If Statements", difficulty: "EASY",
    prompt: "What is printed?",
    code: "x = 10\nif x > 5:\n    print(\"big\")\nelse:\n    print(\"small\")",
    answer: "big", explanation: "10 > 5 is true, so 'big' prints." },
  { type: "MULTIPLE_CHOICE", topic: "If Statements", difficulty: "EASY",
    prompt: "Which operator means 'not equal'?",
    options: ["!=", "<>", "=/=", "!=="], answer: "!=",
    explanation: "`!=` tests inequality in Python." },
  { type: "TRUE_FALSE", topic: "If Statements", difficulty: "MEDIUM",
    prompt: "`True or False` evaluates to True.", answer: "true",
    explanation: "`or` is true if at least one side is true." },
  { type: "CODE_OUTPUT", topic: "Loops", difficulty: "MEDIUM",
    prompt: "What is the last number printed?",
    code: "for i in range(1, 5):\n    print(i)",
    answer: "4", explanation: "range(1,5) yields 1,2,3,4 — stop is exclusive." },
  { type: "MULTIPLE_CHOICE", topic: "Loops", difficulty: "EASY",
    prompt: "Which loop runs while a condition is true?",
    options: ["for", "while", "repeat", "loop"], answer: "while",
    explanation: "`while` repeats as long as its condition holds." },
  { type: "DEBUG", topic: "Loops", difficulty: "HARD",
    prompt: "This loop never ends. Which line of code (the decrement) is missing inside the loop? Answer with the exact statement.",
    code: "n = 3\nwhile n > 0:\n    print(n)\n    # missing line",
    answer: "n -= 1|n = n - 1",
    explanation: "Without decrementing n, the condition stays true forever." },
  { type: "MULTIPLE_CHOICE", topic: "Functions", difficulty: "EASY",
    prompt: "Which keyword sends a value back from a function?",
    options: ["send", "return", "give", "output"], answer: "return",
    explanation: "`return` passes a value back to the caller." },
  { type: "CODE_OUTPUT", topic: "Functions", difficulty: "MEDIUM",
    prompt: "What is printed?",
    code: "def double(x):\n    return x * 2\nprint(double(6))",
    answer: "12", explanation: "double(6) returns 6 * 2 = 12." },
  { type: "SHORT_ANSWER", topic: "Functions", difficulty: "MEDIUM",
    prompt: "What does a Python function return if it has no return statement?",
    answer: "none", explanation: "Functions without a return give back `None`." },
  { type: "CODE_OUTPUT", topic: "Lists", difficulty: "EASY",
    prompt: "What is printed?", code: "a = [3, 6, 9]\nprint(a[-1])",
    answer: "9", explanation: "Index -1 is the last element, 9." },
  { type: "FILL_BLANK", topic: "Lists", difficulty: "EASY",
    prompt: "Get the number of items: count = ____(my_list)", answer: "len",
    explanation: "`len(my_list)` returns the item count." },
  { type: "MULTIPLE_CHOICE", topic: "Lists", difficulty: "MEDIUM",
    prompt: "What does [1,2,3,4][1:3] produce?",
    options: ["[1,2]", "[2,3]", "[2,3,4]", "[1,2,3]"], answer: "[2,3]",
    explanation: "Slicing [1:3] takes indexes 1 and 2 → [2,3]." },
  { type: "CODE_OUTPUT", topic: "Dictionaries", difficulty: "MEDIUM",
    prompt: "What is printed?",
    code: "d = {\"x\": 1}\nd[\"y\"] = 2\nprint(len(d))",
    answer: "2", explanation: "After adding key 'y', the dict has 2 keys." },
  { type: "MULTIPLE_CHOICE", topic: "Dictionaries", difficulty: "MEDIUM",
    prompt: "Which method returns key–value pairs for looping?",
    options: ["keys()", "values()", "items()", "pairs()"], answer: "items()",
    explanation: "`.items()` yields (key, value) tuples." },
  { type: "TRUE_FALSE", topic: "Dictionaries", difficulty: "EASY",
    prompt: "Dictionary keys must be unique.", answer: "true",
    explanation: "Each key appears once; assigning again overwrites the value." },
];

// "Final Boss" — harder, mixed, longer, bigger XP. Reuses the beginner pool
// plus a few tougher questions so it reaches a meatier length.
const bossExtras: SeedQuestion[] = [
  { type: "CODE_OUTPUT", topic: "Loops", difficulty: "HARD",
    prompt: "What is printed?",
    code: "total = 0\nfor i in range(1, 4):\n    for j in range(i):\n        total += 1\nprint(total)",
    answer: "6", explanation: "Inner loop runs 0+1+2... actually 1+2+3 over i=1,2,3 → wait: i=1→1, i=2→2, i=3→3, total 6." },
  { type: "CODE_OUTPUT", topic: "Functions", difficulty: "HARD",
    prompt: "What is printed?",
    code: "def f(n):\n    if n <= 1:\n        return 1\n    return n * f(n - 1)\nprint(f(4))",
    answer: "24", explanation: "Factorial: 4*3*2*1 = 24." },
  { type: "DEBUG", topic: "Lists", difficulty: "HARD",
    prompt: "IndexError occurs. For a list of length 3, what is the largest valid index? Answer the number.",
    code: "items = [10, 20, 30]\nprint(items[3])",
    answer: "2", explanation: "Valid indexes are 0..len-1, so 0,1,2 — the max is 2." },
  { type: "SHORT_ANSWER", topic: "Data Types", difficulty: "HARD",
    prompt: "Name the error type raised by \"3\" + 4 in Python.",
    answer: "typeerror", explanation: "Mixing str and int raises a TypeError." },
];

export const pythonExams: SeedExam[] = [
  {
    title: "Python Beginner Final Exam",
    level: "BEGINNER",
    durationMinutes: 30,
    passingScore: 60,
    xpReward: 250,
    questions: beginnerQuestions,
  },
  {
    title: "🐉 Python Final Boss",
    level: "BEGINNER",
    durationMinutes: 40,
    passingScore: 75,
    isBoss: true,
    xpReward: 600,
    questions: [...beginnerQuestions, ...bossExtras],
  },
];
